package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Saturday, March 4, 2017 3:38:26 PM CET
*/

public interface ChatOperations 
{
  void join (ChatApp.ChatCallback objref, String name);
  void list (ChatApp.ChatCallback objref);
  void post (ChatApp.ChatCallback objref, String msg);
  void leave (ChatApp.ChatCallback objref, boolean silent);
  void game (ChatApp.ChatCallback objref, String color);
  void move (ChatApp.ChatCallback objref, String msg);
} // interface ChatOperations
