package ChatApp;


/**
* ChatApp/ChatCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Saturday, March 4, 2017 2:05:20 PM CET
*/

public interface ChatCallback extends ChatCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatCallback
