package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Friday, March 3, 2017 1:14:21 PM CET
*/

public interface ChatOperations 
{
  String join (ChatApp.ChatCallback objref, String name);
  String list (ChatApp.ChatCallback objref);
  String post (ChatApp.ChatCallback objref, String msg);
  String leave (ChatApp.ChatCallback objref);
} // interface ChatOperations
