package ChatApp;


/**
* ChatApp/ChatCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Monday, March 6, 2017 1:52:33 PM CET
*/

public interface ChatCallback extends ChatCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatCallback
