module ChatApp {
   interface ChatCallback {
      void callback(in string message);
   };
   interface Chat {
      void join(in ChatCallback objref, in string name);
      void list(in ChatCallback objref);
      void post(in ChatCallback objref, in string msg);
      void leave(in ChatCallback objref, in boolean silent);
      void game(in ChatCallback objref, in string color);
      void move(in ChatCallback objref, in string msg);
   };
};
